##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Environment Labeling even tracking for Blue/Green Stepping
on:
  pull_request_target:
    types:
      - labeled
      - unlabeled

permissions:
  contents: write
  packages: read
  statuses: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "A Labeling happened"
