##
# (c) 2021 - CloudopsWorks OÜ - https://docs.cloudops.works/
#
name: Chatops Agent
on:
  issue_comment:
    types:
      - created

permissions:
  issues: write
  contents: write
  packages: read
  statuses: write
  pull-requests: write
  security-events: write

jobs:
  # this one runs only when commenting a pull request
  gitops:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commands: |
            approved
            approve
            lgtm
            cancel
            retry
            continue
          static-args: |
            author=${{ github.actor }}
            pull_request=true
            pull_request_number=${{ github.event.issue.number }}
          
